config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'posts#index'
  # commentator config
  mount Commontator::Engine => '/commontator'
  # for user profile
  resources :users, only: [:show, :index]
  resources :posts do
    member do
      put "like" , to: "posts#liked"
      put "dislike", to: "posts#unliked"
    end
  end
  resources :friends, only: [:index, :destroy]
  resources :friend_requests
  # resources :users do
  #   get :posts
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend_request.rb
class FriendRequest < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validate :not_self
  validate :not_friends
  validate :not_pending

  # validates :user, presence: true
  # validates :friend, presence: true, uniqueness: { scope: :user }

  def accept
    user.friends << friend
    destroy
  end

  private

  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end

  def not_friends
    errors.add(:friend, 'already added') if user.friends.include?(friend)
  end

  def not_pending
    errors.add(:friend, 'request is waiting to be accepted') if user.pending_friends.include?(friend) || friend.pending_friends.include?(user)
  end
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  after_create :create_inverse_relationship
  after_destroy :destroy_inverse_relationship

  belongs_to :user
  belongs_to :friend, class_name: 'User'

  validate :not_self

  validates :user, presence: true
  validates :friend, presence: true, uniqueness: { scope: :user }

  private

  def create_inverse_relationship
    friend.friends << user
  end

  def destroy_inverse_relationship
    friendship = friend.friendships.find_by(friend: user)
    friendship.destroy if friendship
  end

  def not_self
    errors.add(:friend, "can't be equal to user") if user == friend
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user, optional: true

  # commontable
  acts_as_commontable dependent: :destroy
  acts_as_votable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts, dependent: :destroy
  has_many :comments
  # commentator
  acts_as_commontator

  acts_as_voter

  has_many :friend_requests, dependent: :destroy
  has_many :pending_friends, through: :friend_requests, source: :friend

  has_many :friendships, dependent: :destroy
  has_many :friends, through: :friendships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :notification
  before_action :configure_permitted_parameters, if: :devise_controller?

  # to allow access to all pundit method
  include Pundit

  def notification
    @total_request = (FriendRequest.where(friend: current_user)).count
  end

  rescue_from Pundit::NotAuthorizedError, with: :current_user_not_authorized

  private

  def current_user_not_authorized
    flash[:alert] = 'You do are not authorized for this action.'
    redirect_to root_url
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
  end
end

app/controllers/friend_requests_controller.rb
class FriendRequestsController < ApplicationController
  before_action :set_friend_request, except: [:index, :create]

  def create
    friend = User.find(params[:friend_id])
    @friend_request = current_user.friend_requests.new(friend: friend)
    if @friend_request.save
      redirect_to users_path, notice: "Successfully sent friend request!"
    else
      redirect_to users_path
      flash[:error] = @friend_request.errors.full_messages.to_sentence
    end
  end

  def index
    @incoming = FriendRequest.where(friend: current_user)
    @outgoing = current_user.friend_requests
  end

  def show
  end

  def destroy
    @friend_request.destroy
    flash[:success] = "Ignored friend request"
    redirect_to @friend_request
  end

  def update
    @friend_request.accept
    flash[:success] = "Accepted friend request"
    redirect_to @friend_request
  end

  private

  def set_friend_request
    @friend_request = FriendRequest.find(params[:id])
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: :destroy

  def index
    @friends = current_user.friends
  end

  def destroy
    current_user.friends.destroy(@friend)
    flash[:success] = "Removed friend"
    redirect_to current_user
  end

  private

  def set_friend
    @friend = current_user.friends.find(params[:id])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy, :liked, :unliked]
  before_action :authenticate_user!, except: [:show]

  after_action :verify_authorized, except: [:index, :show]

  def index
    # @posts = Post.all.order("created_at DESC")
    friend_ids = "SELECT user_id FROM friendships WHERE  friend_id = :user_id"
    @posts = Post.where("user_id IN (#{friend_ids}) OR user_id = :user_id", user_id: current_user.id).all.order("created_at DESC")
  end

  def new
    @post = current_user.posts.build
    authorize @post
  end

  def create
    @post = current_user.posts.build(post_params)
    authorize @post
    if @post.save
      redirect_to root_path, notice: "Successfully created a new Post!"
    else
      puts @post.errors.full_messages
    end
  end

  def show
  end

  def edit
    authorize @post
  end

  def update
    authorize @post
    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated!"
    else
      render 'edit'
    end
  end

  def destroy
    authorize @post
    @post.destroy
    flash[:success] = "Post deleted"
    redirect_to root_path
  end

  def liked
    @post.liked_by current_user
    authorize @post
    redirect_back(fallback_location:"/")
  end

  def unliked
    @post.unliked_by current_user
    authorize @post
    redirect_back(fallback_location:"/")
  end

  private

  def post_params
    params.require(:post).permit(:description)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  def show
  end

  def index
    @users = User.all.where("id != ?", current_user.id)
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friend_requests_helper.rb
module FriendRequestsHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friend_requests/index.html.erb
<h2>Incoming Friend Requests</h2>
<% unless @incoming.blank? %>
  <% @incoming.each do |i| %>
    <p>
      <%= link_to "#{i.user.name}", i.user %>
      <%= link_to "Accept", friend_request_path(i), method: :put %>
      <%= link_to "Ignore", friend_request_path(i), method: :delete %>
    </p>
  <% end %>
<% end %>
<h2>Pending Friend Requests</h2>
<% @outgoing.each do |p| %>
  <p>
    <%= link_to "#{p.friend.name}", p.friend %>
  </p>
<% end %>

app/views/friends/destroy.html.erb
<h1>Friends#destroy</h1>
<p>Find me in app/views/friends/destroy.html.erb</p>

app/views/friends/index.html.erb
<h1>Friends (<%= @friends.count %>)</h1>
<% @friends.each do |friend| %>
  <p>
    <%= link_to "#{friend.name}", friend %>
    <%= link_to "Remove friend", friend_path(friend.id), method: :delete, data: { confirm: "Are you sure?" } %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFacebook</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, message| %>
      <p><%= message %></p>
    <% end %>
    <%= link_to "Home", root_path %>
    <% if user_signed_in? %>
      <%= link_to "New Post", new_post_path %>
      <%= link_to "Profile", current_user %>
      <%= link_to "Find Friends", users_path %>
      <%= link_to "Notification[#{notification}]", friend_requests_path %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path %>
      <%= link_to "Sign In", new_user_session_path %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.text_field :description, placeholder: "Write a post"%><br />
  <%= f.submit "Post" %>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Your Post</h1>
<%= render 'form' %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <p><%= link_to post.description, post %> by <i><%= link_to "#{post.user.name}", post.user %></i> at <i><%= post.created_at.to_formatted_s(:short) %></i></p>
  <% if current_user.liked? post%>
    <%= link_to "Like", dislike_post_path(post), method: :put %>
  <% else %>
    <%= link_to "Like", like_post_path(post), method: :put %>
  <% end %>
  <%= post.get_likes.size %>
  <%= commontator_thread(post) %>
<% end %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<p><%= @post.description %></p>
by <i><%= @post.user.name %></i> at <i><%= @post.created_at.to_formatted_s(:short) %></i>
<br/>
<% if user_signed_in? %>
  <p>
    <%= link_to "Edit", edit_post_path if policy(@post).edit? %>
    <%= link_to "Delete", post_path, method: :delete, data: { confirm: "Are you sure?" } if policy(@post).destroy? %>
  </p>
<% end %>

app/views/users/index.html.erb
<h1>All Results</h1>
<% @users.each do |user| %>
  <% if current_user.friends.include?(user) || current_user.pending_friends.include?(user) %>

  <% else %>
    <p>
      <%= link_to "#{user.name}", user %>
      <%= link_to "Send request", friend_requests_path(friend_id: user.id), method: :post %>
    </p>
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>'s Profile</h1>
<p>Name: <%= @user.name %></p>
<p>Email: <%= @user.email %></p>
<p>Created at: <%= @user.created_at.to_formatted_s(:long) %></p>
<%= link_to 'Edit Profile', edit_user_registration_path %>
<%= link_to "Friends (#{@user.friends.count})", friends_path %>
</br>
<h3><%= @user.name %>'s posts</h3>
<% @user.posts.sort { |a,b| b.created_at <=> a.created_at }.each do |post| %>
  <p><%= post.description %></p>
  <% if current_user.liked? post%>
    <%= link_to "Like", dislike_post_path(post), method: :put %>
  <% else %>
    <%= link_to "Like", like_post_path(post), method: :put %>
  <% end %>
  <%= post.get_likes.size %>
  <%= commontator_thread(post) %>
<% end %>